name: CI/CD for MCDR Plugin

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build a MCDR Plugin

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          pip-${{ runner.os }}-${{ env.cache-name }}-
          pip-${{ runner.os }}-

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Dev Build
      run: |
        python -m mcdreforged pack -o out

    - uses: actions/upload-artifact@v2
      with:
        path: out/*
